export const systemTokens = {
  color: {
    surface: "#ffffff",
    surfaceRaised: "#f7f8fb",
    text: "#15171c",
    textMuted: "#5f6673",
    border: "#d9dee8",
    action: "#d9232e",
    actionHover: "#b91d27",
    actionText: "#ffffff",
    focus: "#2458d3",
    success: "#147a3f",
    warning: "#8a5a00",
    danger: "#b42318",
  },
  space: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
  },
  radius: {
    sm: "4px",
    md: "8px",
  },
  typography: {
    bodyFamily: "Ubuntu, system-ui, sans-serif",
    titleFamily: "Edenred, Ubuntu, system-ui, sans-serif",
  },
  energy: {
    action: {
      primary: "var(--sys-energy-action-primary)",
    },
    status: {
      success: "var(--sys-energy-status-success)",
      warning: "var(--sys-energy-status-warning)",
      warningForeground: "var(--sys-energy-status-warning-foreground)",
      error: "var(--sys-energy-status-error)",
    },
    surface: {
      primary: "var(--sys-energy-surface-primary)",
      secondary: "var(--sys-energy-surface-secondary)",
      tertiary: "var(--sys-energy-surface-tertiary)",
      sunken: "var(--sys-energy-surface-sunken)",
      accent: "var(--sys-energy-surface-accent)",
    },
    text: {
      primary: "var(--sys-energy-text-primary)",
      secondary: "var(--sys-energy-text-secondary)",
      tertiary: "var(--sys-energy-text-tertiary)",
      onAction: "var(--sys-energy-text-on-action)",
    },
    border: {
      default: "var(--sys-energy-border-default)",
      strong: "var(--sys-energy-border-strong)",
    },
    ref: {
      neutral: {
        50: "var(--ref-energy-neutral-50)",
        100: "var(--ref-energy-neutral-100)",
        200: "var(--ref-energy-neutral-200)",
        300: "var(--ref-energy-neutral-300)",
        400: "var(--ref-energy-neutral-400)",
        500: "var(--ref-energy-neutral-500)",
        600: "var(--ref-energy-neutral-600)",
        700: "var(--ref-energy-neutral-700)",
        800: "var(--ref-energy-neutral-800)",
        900: "var(--ref-energy-neutral-900)",
      },
      blue: {
        50: "var(--ref-energy-blue-50)",
        100: "var(--ref-energy-blue-100)",
        200: "var(--ref-energy-blue-200)",
        300: "var(--ref-energy-blue-300)",
        400: "var(--ref-energy-blue-400)",
        500: "var(--ref-energy-blue-500)",
        600: "var(--ref-energy-blue-600)",
        700: "var(--ref-energy-blue-700)",
        800: "var(--ref-energy-blue-800)",
        900: "var(--ref-energy-blue-900)",
      },
      red: {
        50: "var(--ref-energy-red-50)",
        100: "var(--ref-energy-red-100)",
        200: "var(--ref-energy-red-200)",
        300: "var(--ref-energy-red-300)",
        400: "var(--ref-energy-red-400)",
        500: "var(--ref-energy-red-500)",
        600: "var(--ref-energy-red-600)",
        700: "var(--ref-energy-red-700)",
        800: "var(--ref-energy-red-800)",
        900: "var(--ref-energy-red-900)",
      },
      green: {
        50: "var(--ref-energy-green-50)",
        100: "var(--ref-energy-green-100)",
        200: "var(--ref-energy-green-200)",
        300: "var(--ref-energy-green-300)",
        400: "var(--ref-energy-green-400)",
        500: "var(--ref-energy-green-500)",
        600: "var(--ref-energy-green-600)",
        700: "var(--ref-energy-green-700)",
        800: "var(--ref-energy-green-800)",
        900: "var(--ref-energy-green-900)",
      },
      yellow: {
        50: "var(--ref-energy-yellow-50)",
        100: "var(--ref-energy-yellow-100)",
        200: "var(--ref-energy-yellow-200)",
        300: "var(--ref-energy-yellow-300)",
        400: "var(--ref-energy-yellow-400)",
        500: "var(--ref-energy-yellow-500)",
        600: "var(--ref-energy-yellow-600)",
        700: "var(--ref-energy-yellow-700)",
        800: "var(--ref-energy-yellow-800)",
        900: "var(--ref-energy-yellow-900)",
      },
    },
  },
  voice: {
    family: {
      brand: "var(--ref-voice-family-brand)",
      sans: "var(--ref-voice-family-sans)",
      mono: "var(--ref-voice-family-mono)",
      control: "var(--sys-voice-family-control)",
    },
    weight: {
      regular: "var(--ref-voice-weight-regular)",
      medium: "var(--ref-voice-weight-medium)",
      semibold: "var(--ref-voice-weight-semibold)",
      bold: "var(--ref-voice-weight-bold)",
      black: "var(--ref-voice-weight-black)",
      control: "var(--sys-voice-weight-control)",
    },
    role: {
      displayLg: {
        family: "var(--sys-voice-display-lg-family)",
        weight: "var(--sys-voice-display-lg-weight)",
        size: "var(--sys-voice-display-lg-size)",
        lineHeight: "var(--sys-voice-display-lg-line-height)",
        letterSpacing: "var(--sys-voice-display-lg-letter-spacing)",
      },
      displayMd: {
        family: "var(--sys-voice-display-md-family)",
        weight: "var(--sys-voice-display-md-weight)",
        size: "var(--sys-voice-display-md-size)",
        lineHeight: "var(--sys-voice-display-md-line-height)",
        letterSpacing: "var(--sys-voice-display-md-letter-spacing)",
      },
      displaySm: {
        family: "var(--sys-voice-display-sm-family)",
        weight: "var(--sys-voice-display-sm-weight)",
        size: "var(--sys-voice-display-sm-size)",
        lineHeight: "var(--sys-voice-display-sm-line-height)",
        letterSpacing: "var(--sys-voice-display-sm-letter-spacing)",
      },
      headingLg: {
        family: "var(--sys-voice-heading-lg-family)",
        weight: "var(--sys-voice-heading-lg-weight)",
        size: "var(--sys-voice-heading-lg-size)",
        lineHeight: "var(--sys-voice-heading-lg-line-height)",
        letterSpacing: "var(--sys-voice-heading-lg-letter-spacing)",
      },
      headingMd: {
        family: "var(--sys-voice-heading-md-family)",
        weight: "var(--sys-voice-heading-md-weight)",
        size: "var(--sys-voice-heading-md-size)",
        lineHeight: "var(--sys-voice-heading-md-line-height)",
        letterSpacing: "var(--sys-voice-heading-md-letter-spacing)",
      },
      headingSm: {
        family: "var(--sys-voice-heading-sm-family)",
        weight: "var(--sys-voice-heading-sm-weight)",
        size: "var(--sys-voice-heading-sm-size)",
        lineHeight: "var(--sys-voice-heading-sm-line-height)",
        letterSpacing: "var(--sys-voice-heading-sm-letter-spacing)",
      },
      labelLg: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-control)",
        size: "var(--sys-voice-label-lg-size)",
        lineHeight: "var(--sys-voice-label-lg-line-height)",
      },
      labelMd: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-control)",
        size: "var(--sys-voice-label-md-size)",
        lineHeight: "var(--sys-voice-label-md-line-height)",
      },
      labelSm: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-control)",
        size: "var(--sys-voice-label-sm-size)",
        lineHeight: "var(--sys-voice-label-sm-line-height)",
      },
      paragraphLg: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-regular)",
        size: "var(--sys-voice-paragraph-lg-size)",
        lineHeight: "var(--sys-voice-paragraph-lg-line-height)",
      },
      paragraphMd: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-regular)",
        size: "var(--sys-voice-paragraph-md-size)",
        lineHeight: "var(--sys-voice-paragraph-md-line-height)",
      },
      paragraphSm: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-regular)",
        size: "var(--sys-voice-paragraph-sm-size)",
        lineHeight: "var(--sys-voice-paragraph-sm-line-height)",
      },
      caption: {
        family: "var(--sys-voice-family)",
        weight: "var(--sys-voice-weight-medium)",
        size: "var(--sys-voice-caption-size)",
        lineHeight: "var(--sys-voice-caption-line-height)",
      },
      code: {
        family: "var(--sys-voice-family-mono)",
        weight: "var(--sys-voice-weight-semibold)",
        size: "var(--sys-voice-code-size)",
        lineHeight: "var(--sys-voice-code-line-height)",
      },
      numeral: {
        family: "var(--sys-voice-numeral-family)",
        weight: "var(--sys-voice-numeral-weight)",
        lineHeight: "var(--sys-voice-numeral-line-height)",
      },
    },
  },
  frame: {
    space: {
      0: "var(--ref-frame-space-0)",
      1: "var(--ref-frame-space-1)",
      2: "var(--ref-frame-space-2)",
      3: "var(--ref-frame-space-3)",
      4: "var(--ref-frame-space-4)",
      5: "var(--ref-frame-space-5)",
      6: "var(--ref-frame-space-6)",
      7: "var(--ref-frame-space-7)",
      8: "var(--ref-frame-space-8)",
      9: "var(--ref-frame-space-9)",
      10: "var(--ref-frame-space-10)",
      11: "var(--ref-frame-space-11)",
      12: "var(--ref-frame-space-12)",
      16: "var(--ref-frame-space-16)",
      20: "var(--ref-frame-space-20)",
      24: "var(--ref-frame-space-24)",
      32: "var(--ref-frame-space-32)",
      40: "var(--ref-frame-space-40)",
      micro: "var(--ref-frame-space-micro)",
    },
    radius: {
      0: "var(--ref-frame-radius-0)",
      1: "var(--ref-frame-radius-1)",
      2: "var(--ref-frame-radius-2)",
      3: "var(--ref-frame-radius-3)",
      4: "var(--ref-frame-radius-4)",
      5: "var(--ref-frame-radius-5)",
      6: "var(--ref-frame-radius-6)",
      7: "var(--ref-frame-radius-7)",
      8: "var(--ref-frame-radius-8)",
      9: "var(--ref-frame-radius-9)",
      10: "var(--ref-frame-radius-10)",
      11: "var(--ref-frame-radius-11)",
      12: "var(--ref-frame-radius-12)",
      control: "var(--sys-frame-radius-control)",
      container: "var(--sys-frame-radius-container)",
      surface: "var(--sys-frame-radius-surface)",
      full: "var(--sys-frame-radius-full)",
    },
    size: {
      controlSm: "var(--sys-frame-height-control-sm)",
      controlMd: "var(--sys-frame-height-control-md)",
      controlLg: "var(--sys-frame-height-control-lg)",
      row: "var(--density-row-height)",
      sidebarExpanded: "var(--sys-frame-sidebar-expanded)",
      sidebarCollapsed: "var(--sys-frame-sidebar-collapsed)",
      contentMax: "var(--sys-frame-content-max)",
      contentDialog: "var(--sys-frame-content-dialog)",
    },
    density: {
      controlHeight: "var(--density-control-height)",
      controlPaddingX: "var(--density-control-padding-x)",
      controlPaddingY: "var(--density-control-padding-y)",
      panelPadding: "var(--density-panel-padding)",
      cardPadding: "var(--density-card-padding)",
      surfacePadding: "var(--density-surface-padding)",
      componentGap: "var(--density-component-gap)",
      componentGapLg: "var(--density-component-gap-lg)",
      subsectionGap: "var(--density-subsection-gap)",
      sectionGap: "var(--density-section-gap)",
      pageGap: "var(--density-page-gap)",
      rowHeight: "var(--density-row-height)",
    },
    grid: {
      sm: {
        columns: "var(--sys-frame-grid-sm-columns)",
        gutter: "var(--sys-frame-grid-sm-gutter)",
        margin: "var(--sys-frame-grid-sm-margin)",
      },
      md: {
        columns: "var(--sys-frame-grid-md-columns)",
        gutter: "var(--sys-frame-grid-md-gutter)",
        margin: "var(--sys-frame-grid-md-margin)",
      },
      lg: {
        columns: "var(--sys-frame-grid-lg-columns)",
        gutter: "var(--sys-frame-grid-lg-gutter)",
        margin: "var(--sys-frame-grid-lg-margin)",
        maxWidth: "var(--sys-frame-grid-lg-max-width)",
      },
    },
    border: {
      thin: "var(--sys-frame-border-thin)",
      control: "var(--sys-frame-border-control)",
      medium: "var(--sys-frame-border-medium)",
      indicator: "var(--sys-frame-border-indicator)",
    },
  },
  depth: {
    overlay: "var(--sys-depth-overlay)",
    backdropBlur: "var(--sys-depth-backdrop-blur)",
    blur: {
      sm: "var(--ref-depth-blur-sm)",
      md: "var(--ref-depth-blur-md)",
      lg: "var(--ref-depth-blur-lg)",
      topbar: "var(--sys-depth-blur-topbar)",
    },
    z: {
      dropdown: "var(--sys-depth-z-dropdown)",
      sticky: "var(--sys-depth-z-sticky)",
      overlay: "var(--sys-depth-z-overlay)",
      dialog: "var(--sys-depth-z-dialog)",
      toast: "var(--sys-depth-z-toast)",
    },
    lift: {
      subtle: "var(--sys-depth-lift-subtle)",
      rest: "var(--sys-depth-lift-rest)",
      raised: "var(--sys-depth-lift-raised)",
      overlay: "var(--sys-depth-lift-overlay)",
    },
    elevation: {
      0: "var(--sys-depth-elevation-0)",
      1: "var(--sys-depth-elevation-1)",
      2: "var(--sys-depth-elevation-2)",
      3: "var(--sys-depth-elevation-3)",
      4: "var(--sys-depth-elevation-4)",
    },
  },
  tone: {
    color: {
      neutral: "var(--sys-tone-neutral-color)",
      assistive: "var(--sys-tone-assistive-color)",
      urgent: "var(--sys-tone-urgent-color)",
      repair: "var(--sys-tone-repair-color)",
      confirm: "var(--sys-tone-confirm-color)",
    },
    weight: {
      neutral: "var(--sys-tone-neutral-weight)",
      assistive: "var(--sys-tone-assistive-weight)",
      urgent: "var(--sys-tone-urgent-weight)",
      repair: "var(--sys-tone-repair-weight)",
    },
  },
  accessibility: {
    focus: {
      ring: "var(--sys-a11y-focus-ring)",
      offset: "var(--sys-a11y-focus-offset)",
    },
    touch: {
      targetMin: "var(--sys-a11y-touch-target-min)",
    },
    contrast: {
      aa: "var(--sys-a11y-contrast-aa)",
      large: "var(--ref-a11y-contrast-large)",
    },
    motion: {
      reducedDuration: "var(--ref-a11y-motion-reduced-duration)",
      duration: "var(--sys-a11y-motion-duration)",
    },
  },
  symbol: {
    family: {
      material: "var(--ref-symbol-family-material)",
      default: "var(--sys-symbol-family)",
    },
    size: {
      xs: "var(--ref-symbol-size-xs)",
      sm: "var(--sys-symbol-size-sm)",
      md: "var(--sys-symbol-size-md)",
      lg: "var(--sys-symbol-size-lg)",
      xl: "var(--ref-symbol-size-xl)",
      gridBase: "var(--ref-symbol-grid-base)",
      liveArea: "var(--ref-symbol-live-area)",
    },
    stroke: "var(--ref-symbol-stroke)",
    color: {
      action: "var(--sys-symbol-color-action)",
      status: "var(--sys-symbol-color-status)",
      warning: "var(--sys-symbol-color-warning)",
      danger: "var(--sys-symbol-color-danger)",
      muted: "var(--sys-symbol-color-muted)",
    },
  },
  iconography: {
    family: "var(--sys-iconography-family)",
    size: {
      sm: "var(--sys-iconography-size-sm)",
      md: "var(--sys-iconography-size-md)",
      lg: "var(--sys-iconography-size-lg)",
    },
    color: {
      action: "var(--sys-iconography-color-action)",
      navigation: "var(--sys-iconography-color-navigation)",
      status: "var(--sys-iconography-color-status)",
      warning: "var(--sys-iconography-color-warning)",
      danger: "var(--sys-iconography-color-danger)",
      muted: "var(--sys-iconography-color-muted)",
      disabled: "var(--sys-iconography-color-disabled)",
    },
    accessibility: {
      touchTargetMin: "var(--sys-iconography-touch-target-min)",
      focusRing: "var(--sys-iconography-focus-ring)",
      focusOffset: "var(--sys-iconography-focus-offset)",
    },
  },
  growth: {
    stage: {
      seed: "var(--ref-growth-stage-seed)",
      stable: "var(--ref-growth-stage-stable)",
      measured: "var(--ref-growth-stage-measured)",
      deprecated: "var(--ref-growth-stage-deprecated)",
    },
    color: {
      seed: "var(--sys-growth-stage-seed-color)",
      stable: "var(--sys-growth-stage-stable-color)",
      measured: "var(--sys-growth-stage-measured-color)",
      deprecated: "var(--sys-growth-stage-deprecated-color)",
    },
    event: {
      font: "var(--sys-growth-event-font)",
    },
  },
  momentum: {
    duration: {
      instant: "var(--ref-momentum-duration-instant)",
      fast: "var(--sys-momentum-duration-fast)",
      default: "var(--sys-momentum-duration-default)",
      slow: "var(--sys-momentum-duration-slow)",
      critical: "var(--sys-momentum-duration-critical)",
      touch: "var(--sys-momentum-duration-touch)",
      cycle: "var(--ref-momentum-duration-cycle)",
    },
    easing: {
      touch: "var(--sys-momentum-easing-touch)",
      standard: "var(--sys-momentum-easing-standard)",
      enter: "var(--sys-momentum-easing-enter)",
      move: "var(--sys-momentum-easing-move)",
      exit: "var(--sys-momentum-easing-exit)",
      linear: "var(--ref-momentum-easing-linear)",
    },
    scale: {
      hover: "var(--sys-momentum-scale-hover)",
      press: "var(--sys-momentum-scale-press)",
    },
    lift: {
      hover: "var(--sys-momentum-lift-hover)",
    },
    stagger: {
      fast: "var(--ref-momentum-stagger-fast)",
      normal: "var(--ref-momentum-stagger-normal)",
      slow: "var(--ref-momentum-stagger-slow)",
    },
    transition: {
      touch: "var(--sys-momentum-transition-touch)",
      fast: "var(--sys-momentum-transition-fast)",
      default: "var(--sys-momentum-transition-default)",
      slow: "var(--sys-momentum-transition-slow)",
    },
  },
  state: {
    opacity: {
      disabled: "var(--sys-state-disabled-opacity)",
      muted: "var(--sys-state-muted-opacity)",
      faint: "var(--ref-state-opacity-faint)",
      subtle: "var(--ref-state-opacity-subtle)",
      low: "var(--ref-state-opacity-low)",
      soft: "var(--ref-state-opacity-soft)",
    },
    overlay: {
      hover: "var(--sys-state-hover-overlay)",
      pressed: "var(--sys-state-pressed-overlay)",
      selected: "var(--sys-state-selected-overlay)",
    },
    focus: {
      ring: "var(--sys-state-focus-ring)",
      offset: "var(--sys-state-focus-offset)",
      width: "var(--ref-state-focus-ring-width)",
    },
    loading: {
      spin: "var(--sys-state-loading-spin)",
    },
    precedence: {
      disabled: "var(--ref-state-precedence-disabled)",
      loading: "var(--ref-state-precedence-loading)",
      error: "var(--ref-state-precedence-error)",
      focus: "var(--ref-state-precedence-focus)",
      hover: "var(--ref-state-precedence-hover)",
    },
  },
};

export function cssVar(name) {
  return `var(--sys-${name})`;
}
