#!/usr/bin/env node
/**
 * Flow Design System — token pipeline.
 * Single source of truth: platforms/flow.tokens.json (W3C Design Tokens format).
 * Generates:
 *   - platforms/angular/_flow-tokens.scss   (SCSS variables, for Angular/any Sass build)
 *   - platforms/flutter/flow_tokens.dart    (Dart consts + FlowScheme light/dark)
 *
 * Run with Node 18+: `node platforms/build-tokens.mjs`
 * No dependencies — uses only Node's fs/path. Re-run after editing flow.tokens.json
 * (or tokens/*.css, if you edit those first — keep flow.tokens.json as the master and
 * mirror changes there) to keep every platform in sync.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, 'flow.tokens.json');
const SCSS_OUT = join(__dirname, 'angular', '_flow-tokens.scss');
const DART_OUT = join(__dirname, 'flutter', 'flow_tokens.dart');

const raw = JSON.parse(readFileSync(SRC, 'utf8'));
const root = raw.flow;

// ---- Resolve {flow.color.red.500} references against the raw tree ----
function resolveRef(ref) {
  const path = ref.slice(1, -1).split('.'); // "flow.color.red.500" -> ["flow","color","red","500"]
  let node = raw;
  for (const key of path) node = node && node[key];
  if (!node) throw new Error('Unresolved token reference: ' + ref);
  return typeof node.$value === 'string' && node.$value.startsWith('{') ? resolveRef(node.$value) : node.$value;
}
function resolveValue(v) {
  return typeof v === 'string' && v.startsWith('{') ? resolveRef(v) : v;
}

// ---- Walk a subtree, calling onLeaf(dotPath, resolvedValue, $type) for every token ----
function walk(node, prefix, onLeaf) {
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      onLeaf([...prefix, key], resolveValue(val.$value), val.$type);
    } else if (val && typeof val === 'object') {
      walk(val, [...prefix, key], onLeaf);
    }
  }
}

// kebab-case path for SCSS ($red-500), camelCase for Dart (red500)
const kebab = (parts) => parts.join('-');
const camel = (parts) => parts[0] + parts.slice(1).map(p => p[0].toUpperCase() + p.slice(1)).join('');

function isHexOrRgba(v) {
  return typeof v === 'string' && (/^#([0-9a-f]{3,8})$/i.test(v) || /^rgba?\(/i.test(v));
}
function hexToDartColor(hex) {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map(c => c + c).join('');
  if (h.length === 6) h = 'FF' + h; // opaque
  return '0x' + h.toUpperCase();
}

// ================= Collect tokens =================
const palette = [];      // flow.color.* -> flat swatches
const semanticLight = []; // flow.semantic.light.*
const semanticDark = [];  // flow.semantic.dark.*
const fontSize = [];
const space = [];
const radius = [];
const duration = [];
const easing = [];

if (root.color) walk(root.color, [], (p, v) => palette.push({ path: p, value: v }));
if (root.semantic?.light) walk(root.semantic.light, [], (p, v) => semanticLight.push({ path: p, value: v }));
if (root.semantic?.dark) walk(root.semantic.dark, [], (p, v) => semanticDark.push({ path: p, value: v }));
if (root.fontSize) walk(root.fontSize, [], (p, v) => fontSize.push({ path: p, value: v }));
if (root.space) walk(root.space, [], (p, v) => space.push({ path: p, value: v }));
if (root.radius) walk(root.radius, [], (p, v) => radius.push({ path: p, value: v }));
if (root.duration) walk(root.duration, [], (p, v) => duration.push({ path: p, value: v }));
if (root.easing) walk(root.easing, [], (p, v) => easing.push({ path: p, value: v }));

// ================= SCSS =================
let scss = `// Flow Design System · Angular/SCSS tokens
// GENERATED by platforms/build-tokens.mjs from flow.tokens.json — do not hand-edit.
// Usage: @use 'flow-tokens' as flow;  →  color: flow.$text-primary;
// Semantic values are exposed as CSS custom properties by tokens/colors.css (+ tokens/dark.css) —
// prefer var(--text-primary) in component styles so dark mode works for free; use these
// Sass variables only for build-time needs (e.g. computing a derived value at compile time).

// ---- Base palette ----
`;
for (const { path, value } of palette) scss += `$${kebab(path)}: ${value};\n`;

scss += `\n// ---- Semantic (light / Canvas) ----\n`;
for (const { path, value } of semanticLight) scss += `$${kebab(['light', ...path])}: ${value};\n`;
scss += `\n// ---- Semantic (modo oscuro) ----\n`;
for (const { path, value } of semanticDark) scss += `$${kebab(['dark', ...path])}: ${value};\n`;

if (fontSize.length) {
  scss += `\n// ---- Type scale ----\n`;
  for (const { path, value } of fontSize) scss += `$font-size-${kebab(path)}: ${value};\n`;
}
if (space.length) {
  scss += `\n// ---- Space scale ----\n$space: (`;
  scss += space.map(({ path, value }) => `${path.join('')}: ${value}`).join(', ');
  scss += `);\n`;
}
if (radius.length) {
  scss += `\n// ---- Radius ----\n`;
  for (const { path, value } of radius) scss += `$radius-${kebab(path)}: ${value};\n`;
}
if (duration.length) {
  scss += `\n// ---- Duration ----\n`;
  for (const { path, value } of duration) scss += `$dur-${kebab(path)}: ${value};\n`;
}
if (easing.length) {
  scss += `\n// ---- Easing ----\n`;
  for (const { path, value } of easing) {
    const v = Array.isArray(value) ? `cubic-bezier(${value.join(', ')})` : value;
    scss += `$ease-${kebab(path)}: ${v};\n`;
  }
}

writeFileSync(SCSS_OUT, scss);

// ================= Dart =================
let dart = `// Flow Design System · Flutter tokens
// GENERATED by platforms/build-tokens.mjs from flow.tokens.json — do not hand-edit.
import 'package:flutter/material.dart';

abstract final class FlowColors {
`;
for (const { path, value } of palette) {
  if (isHexOrRgba(value) && value.startsWith('#')) {
    dart += `  static const ${camel(path)} = Color(${hexToDartColor(value)});\n`;
  }
}
dart += `}\n\n`;

function schemeFields(entries) {
  return entries.map(({ path }) => camel(path)).join(', ');
}
function schemeCtorArgs(entries) {
  return entries.map(({ path }) => `required this.${camel(path)}`).join(', ');
}
function schemeValues(entries) {
  return entries.map(({ path, value }) => {
    if (isHexOrRgba(value) && value.startsWith('#')) return `${camel(path)}: Color(${hexToDartColor(value)})`;
    // rgba(...) alpha colors: leave a TODO — Flutter needs Color.fromRGBO, out of scope for auto-conversion of every case
    return `${camel(path)}: Color(0xFF000000) /* TODO: convert '${value}' manually */`;
  }).join(',\n      ');
}

dart += `/// Semantic scheme — Canvas en claro y en modo oscuro. Fields generated from
/// flow.semantic.light/dark in flow.tokens.json.
class FlowScheme {
  final Color ${schemeFields(semanticLight).replace(/, /g, ',\n      ')};
  const FlowScheme._({
    ${schemeCtorArgs(semanticLight).replace(/, /g, ',\n    ')}
  });

  static const light = FlowScheme._(
    ${schemeValues(semanticLight)}
  );

  static const dark = FlowScheme._(
    ${schemeValues(semanticDark)}
  );
}
`;

if (fontSize.length) {
  dart += `\nabstract final class FlowFontSize {\n`;
  for (const { path, value } of fontSize) dart += `  static const double ${camel(path)} = ${parseFloat(value)};\n`;
  dart += `}\n`;
}
if (space.length) {
  dart += `\nabstract final class FlowSpace {\n`;
  for (const { path, value } of space) dart += `  static const double s${path.join('')} = ${parseFloat(value)};\n`;
  dart += `}\n`;
}
if (radius.length) {
  dart += `\nabstract final class FlowRadius {\n`;
  for (const { path, value } of radius) dart += `  static const double ${camel(path)} = ${parseFloat(value) || 9999};\n`;
  dart += `}\n`;
}
if (duration.length) {
  dart += `\nabstract final class FlowDuration {\n`;
  for (const { path, value } of duration) dart += `  static const ${camel(path)} = Duration(milliseconds: ${parseInt(value)});\n`;
  dart += `}\n`;
}
if (easing.length) {
  dart += `\n// Easing curves — use with Curves.easeInOutCubic or a package like\n// flutter_animate's Cubic() for exact cubic-bezier control points:\n`;
  for (const { path, value } of easing) {
    const v = Array.isArray(value) ? value.join(', ') : value;
    dart += `// ${camel(path)}: Cubic(${v})\n`;
  }
}

writeFileSync(DART_OUT, dart);

console.log(`Wrote ${SCSS_OUT}`);
console.log(`Wrote ${DART_OUT}`);
console.log(`Tokens: ${palette.length} palette, ${semanticLight.length} semantic(light), ${semanticDark.length} semantic(dark), ${fontSize.length} fontSize, ${space.length} space, ${radius.length} radius, ${duration.length} duration, ${easing.length} easing.`);
