// Flow Design System · Flutter tokens
// GENERATED by platforms/build-tokens.mjs from flow.tokens.json — do not hand-edit.
import 'package:flutter/material.dart';

abstract final class FlowColors {
  static const red50 = Color(0xFFFFEDE9);
  static const red100 = Color(0xFFFFDAD2);
  static const red400 = Color(0xFFFF6A52);
  static const red500 = Color(0xFFFF3617);
  static const red600 = Color(0xFFE62D10);
  static const ink300 = Color(0xFFB5B1AA);
  static const ink500 = Color(0xFF6B6A6E);
  static const ink700 = Color(0xFF3B3A3E);
  static const ink900 = Color(0xFF17171A);
  static const sand25 = Color(0xFFFAF9F7);
  static const sand50 = Color(0xFFF3F1ED);
  static const sand100 = Color(0xFFEEEBE6);
  static const sand200 = Color(0xFFE0DDD7);
  static const green50 = Color(0xFFE4F7EE);
  static const green500 = Color(0xFF12B76A);
  static const green600 = Color(0xFF0E8A50);
  static const amber50 = Color(0xFFFCF0DC);
  static const amber500 = Color(0xFFE8930C);
  static const amber600 = Color(0xFFB26A00);
  static const blue50 = Color(0xFFE7F0FE);
  static const blue500 = Color(0xFF2E7CF6);
  static const blue600 = Color(0xFF175CD3);
  static const danger50 = Color(0xFFFEECEA);
  static const danger500 = Color(0xFFD92D20);
  static const danger600 = Color(0xFFB42318);
}

/// Semantic scheme — Canvas en claro y en modo oscuro. Fields generated from
/// flow.semantic.light/dark in flow.tokens.json.
class FlowScheme {
  final Color surfaceCanvas,
      surfaceCard,
      surfaceSunken,
      surfaceInverse,
      surfaceAccentSubtle,
      textPrimary,
      textSecondary,
      textMuted,
      textOnAccent,
      textAccent,
      borderSubtle,
      borderDefault,
      borderStrong,
      borderFocus,
      actionPrimary,
      actionPrimaryHover,
      actionAccent,
      actionAccentHover;
  const FlowScheme._({
    required this.surfaceCanvas,
    required this.surfaceCard,
    required this.surfaceSunken,
    required this.surfaceInverse,
    required this.surfaceAccentSubtle,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.textOnAccent,
    required this.textAccent,
    required this.borderSubtle,
    required this.borderDefault,
    required this.borderStrong,
    required this.borderFocus,
    required this.actionPrimary,
    required this.actionPrimaryHover,
    required this.actionAccent,
    required this.actionAccentHover
  });

  static const light = FlowScheme._(
    surfaceCanvas: Color(0xFFFAF9F7),
      surfaceCard: Color(0xFFFFFFFF),
      surfaceSunken: Color(0xFFF3F1ED),
      surfaceInverse: Color(0xFF17171A),
      surfaceAccentSubtle: Color(0xFFFFEDE9),
      textPrimary: Color(0xFF17171A),
      textSecondary: Color(0xFF55534E),
      textMuted: Color(0xFF8A8781),
      textOnAccent: Color(0xFFFFFFFF),
      textAccent: Color(0xFFE62D10),
      borderSubtle: Color(0xFFEEEBE6),
      borderDefault: Color(0xFFE0DDD7),
      borderStrong: Color(0xFFB5B1AA),
      borderFocus: Color(0xFFFF3617),
      actionPrimary: Color(0xFF17171A),
      actionPrimaryHover: Color(0xFF000000),
      actionAccent: Color(0xFFFF3617),
      actionAccentHover: Color(0xFFE62D10)
  );

  static const dark = FlowScheme._(
    surfaceCanvas: Color(0xFF131315),
      surfaceCard: Color(0xFF1C1C1F),
      surfaceSunken: Color(0xFF18181B),
      surfaceInverse: Color(0xFFF4F3F1),
      surfaceAccentSubtle: Color(0xFF000000) /* TODO: convert 'rgba(255,54,23,0.14)' manually */,
      textPrimary: Color(0xFFF4F3F1),
      textSecondary: Color(0xFFB9B7B2),
      textMuted: Color(0xFF7C7A76),
      textOnAccent: Color(0xFFFFFFFF),
      textAccent: Color(0xFFFF6A52),
      borderSubtle: Color(0xFF26262A),
      borderDefault: Color(0xFF313136),
      borderStrong: Color(0xFF4A4A50),
      borderFocus: Color(0xFFFF6A52),
      actionPrimary: Color(0xFFF4F3F1),
      actionPrimaryHover: Color(0xFFFFFFFF),
      actionAccent: Color(0xFFFF3617),
      actionAccentHover: Color(0xFFFF4A2E)
  );
}

abstract final class FlowFontSize {
  static const double displayXl = 56;
  static const double display = 40;
  static const double titleLg = 28;
  static const double title = 20;
  static const double titleSm = 16;
  static const double body = 14;
  static const double caption = 12;
  static const double overline = 11;
  static const double data = 13;
  static const double dataLg = 26;
}

abstract final class FlowSpace {
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
}

abstract final class FlowRadius {
  static const double xs = 8;
  static const double sm = 12;
  static const double md = 16;
  static const double lg = 20;
  static const double xl = 28;
  static const double pill = 999;
}

abstract final class FlowDuration {
  static const instant = Duration(milliseconds: 100);
  static const fast = Duration(milliseconds: 160);
  static const base = Duration(milliseconds: 240);
  static const slow = Duration(milliseconds: 400);
}

// Easing curves — use with Curves.easeInOutCubic or a package like
// flutter_animate's Cubic() for exact cubic-bezier control points:
// spring: Cubic(0.34, 1.56, 0.64, 1)
// out: Cubic(0.22, 1, 0.36, 1)
// inOut: Cubic(0.65, 0, 0.35, 1)
