#!/usr/bin/env node
/**
 * Flow token pipeline — single DTCG source of truth (tokens/*.json) → every platform.
 *
 * Chain: ref (absolutes) → sys (semantic, theme+density aware) → comp (per component).
 * Themes: canvas (light, default), asphalt (dark), brutal. Density: default / compact / comfortable.
 *
 * Style Dictionary v4 drives the flagship CSS artifact via a custom format that emits the
 * ref→sys→comp chain as native CSS custom-property references (so a [data-theme] swap re-themes
 * everything with zero JS). A small in-file resolver produces the JSON / SCSS / Dart / TS outputs.
 *
 * Run: `node build.mjs`  (Node 18+). Re-run after editing any tokens/*.json.
 */
import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const T = join(__dirname, "tokens");
const DIST = join(__dirname, "dist");
const PARTS = join(DIST, "parts");

// ---------- naming ----------
const kebab = (path) =>
  path
    .join("-")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase();
const varName = (path) => "--" + kebab(path);
const refToVar = (ref) => `var(${varName(ref.slice(1, -1).split("."))})`;
const isRef = (v) => typeof v === "string" && v.startsWith("{") && v.endsWith("}");

// ---------- Style Dictionary: custom CSS format that preserves the token chain ----------
// Emit straight from the authored value: {ref.*} → var(--ref-*), otherwise the literal.
// This preserves the ref→sys→comp chain as native CSS custom-property references without
// relying on Style Dictionary's value resolution (which we deliberately don't want for CSS).
function emitValue(token) {
  const orig = token.original?.$value ?? token.original?.value;
  return isRef(orig) ? refToVar(orig) : String(orig);
}
StyleDictionary.registerFormat({
  name: "flow/css-vars",
  format: async ({ dictionary, options }) => {
    const selector = options.selector ?? ":root";
    const lines = dictionary.allTokens.map((t) => `  ${varName(t.path)}: ${emitValue(t)};`);
    return `${selector} {\n${lines.join("\n")}\n}\n`;
  },
});

const src = (f) => join(T, f);
const top = (seg) => (t) => t.path[0] === seg;
const fromFile = (name) => (t) => (t.filePath || "").endsWith(name);

async function pass({ sources, destination, filter, selector }) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: sources,
    platforms: {
      css: {
        transforms: [],
        buildPath: PARTS + "/",
        files: [{ destination, format: "flow/css-vars", filter, options: { selector } }],
      },
    },
    log: { verbosity: "silent", warnings: "disabled" },
  });
  await sd.buildAllPlatforms();
  return readFileSync(join(PARTS, destination), "utf8");
}

// ---------- lightweight resolver for non-CSS outputs ----------
function loadMerged(files) {
  const tree = {};
  const deepMerge = (a, b) => {
    for (const [k, v] of Object.entries(b)) {
      if (v && typeof v === "object" && !("$value" in v)) {
        a[k] = a[k] || {};
        deepMerge(a[k], v);
      } else a[k] = v;
    }
    return a;
  };
  for (const f of files) deepMerge(tree, JSON.parse(readFileSync(src(f), "utf8")));
  return tree;
}
function makeResolver(tree) {
  const get = (path) => path.split(".").reduce((n, k) => n && n[k], tree);
  const resolve = (v) => {
    if (isRef(v)) {
      const node = get(v.slice(1, -1));
      return resolve(node.$value);
    }
    return v;
  };
  const flat = {};
  const walk = (node, path) => {
    for (const [k, v] of Object.entries(node)) {
      if (k.startsWith("$")) continue;
      if (v && typeof v === "object" && "$value" in v)
        flat[[...path, k].join(".")] = resolve(v.$value);
      else if (v && typeof v === "object") walk(v, [...path, k]);
    }
  };
  walk(tree, []);
  return flat; // dot.path -> resolved value
}

// ---------- build ----------
rmSync(DIST, { recursive: true, force: true });
mkdirSync(PARTS, { recursive: true });

const cssParts = [];
cssParts.push("/* Flow Design System — GENERATED by packages/tokens/build.mjs. Do not edit. */\n");
cssParts.push(
  await pass({
    sources: [src("ref.json")],
    destination: "ref.css",
    filter: top("ref"),
    selector: ":root",
  }),
);
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("sys.base.json")],
    destination: "sys-base.css",
    filter: top("sys"),
    selector: ":root",
  }),
);
// Component tokens are emitted under EVERY theme/density scope, not just :root. CSS custom
// properties resolve their var() references at the element where they are declared, so a
// comp token defined only at :root would freeze the default (Canvas) sys values and ignore a
// [data-theme]/[data-density] set on a subtree. Re-declaring comp under each scope lets it
// re-resolve against that scope's sys values.
const COMP_SCOPES = [
  ":root",
  '[data-theme="canvas"]',
  '[data-theme="asphalt"]',
  '[data-theme="brutal"]',
  '[data-density="compact"]',
  '[data-density="comfortable"]',
].join(",\n");
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("sys.base.json"), src("sys.canvas.json"), src("comp.json")],
    destination: "comp.css",
    filter: top("comp"),
    selector: COMP_SCOPES,
  }),
);
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("sys.canvas.json")],
    destination: "sys-canvas.css",
    filter: fromFile("sys.canvas.json"),
    selector: ':root,\n[data-theme="canvas"]',
  }),
);
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("sys.asphalt.json")],
    destination: "sys-asphalt.css",
    filter: fromFile("sys.asphalt.json"),
    selector: '[data-theme="asphalt"]',
  }),
);
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("sys.brutal.json")],
    destination: "sys-brutal.css",
    filter: fromFile("sys.brutal.json"),
    selector: '[data-theme="brutal"]',
  }),
);
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("density.compact.json")],
    destination: "density-compact.css",
    filter: fromFile("density.compact.json"),
    selector: '[data-density="compact"]',
  }),
);
cssParts.push(
  await pass({
    sources: [src("ref.json"), src("density.comfortable.json")],
    destination: "density-comfortable.css",
    filter: fromFile("density.comfortable.json"),
    selector: '[data-density="comfortable"]',
  }),
);

cssParts.push(`@media (prefers-reduced-motion: reduce) {
  :root {
    --sys-motion-dur-instant: 1ms;
    --sys-motion-dur-fast: 1ms;
    --sys-motion-dur-base: 1ms;
    --sys-motion-dur-slow: 1ms;
    --sys-motion-lift-hover: none;
    --sys-motion-press-scale: none;
    --sys-motion-hover-scale: none;
  }
}
`);

mkdirSync(join(DIST, "scss"), { recursive: true });
mkdirSync(join(DIST, "flutter"), { recursive: true });
writeFileSync(join(DIST, "tokens.css"), cssParts.join("\n"));
rmSync(PARTS, { recursive: true, force: true });

// ----- resolved trees per theme (for JSON/SCSS/Dart/TS) -----
const canvas = makeResolver(
  loadMerged(["ref.json", "sys.base.json", "sys.canvas.json", "comp.json"]),
);
const asphalt = makeResolver(
  loadMerged(["ref.json", "sys.base.json", "sys.asphalt.json", "comp.json"]),
);
const brutal = makeResolver(
  loadMerged(["ref.json", "sys.base.json", "sys.brutal.json", "comp.json"]),
);

// JSON (resolved canvas, dot-path map) + all themes (for contrast tests / tooling)
writeFileSync(join(DIST, "tokens.json"), JSON.stringify(canvas, null, 2) + "\n");
writeFileSync(
  join(DIST, "themes.json"),
  JSON.stringify({ canvas, asphalt, brutal }, null, 2) + "\n",
);

// JS + d.ts (typed, resolved canvas) — consumable entry point
writeFileSync(
  join(DIST, "index.js"),
  `// GENERATED by packages/tokens/build.mjs. Do not edit.\n` +
    `export const tokens = ${JSON.stringify(canvas, null, 2)};\n`,
);
writeFileSync(
  join(DIST, "index.d.ts"),
  `// GENERATED by packages/tokens/build.mjs. Do not edit.\n` +
    `export declare const tokens: Record<string, string>;\n` +
    `export type TokenName = string;\n`,
);

// SCSS (flat vars per theme; for Angular/Sass builds)
const scssBlock = (name, map) =>
  `// ---- ${name} ----\n` +
  Object.entries(map)
    .map(([k, v]) => `$${name}-${k.replace(/\./g, "-")}: ${v};`)
    .join("\n") +
  "\n";
writeFileSync(
  join(DIST, "scss", "_flow.scss"),
  `// Flow Design System · SCSS tokens — GENERATED. Prefer CSS custom properties for theming.\n` +
    scssBlock("canvas", canvas) +
    scssBlock("asphalt", asphalt) +
    scssBlock("brutal", brutal),
);

// Dart (Flutter): ref color consts + per-theme scheme color maps
const hexToDart = (hex) => {
  let h = hex.replace("#", "");
  if (h.length === 3)
    h = h
      .split("")
      .map((c) => c + c)
      .join("");
  if (h.length === 6) h = "FF" + h;
  return "0x" + h.toUpperCase();
};
const colorEntries = (map) =>
  Object.entries(map).filter(
    ([k, v]) =>
      k.startsWith("sys.") &&
      /color|surface|text|border|action|status/.test(k) &&
      typeof v === "string" &&
      v.startsWith("#"),
  );
const dartScheme = (name, map) =>
  `  static const Map<String, Color> ${name} = {\n` +
  colorEntries(map)
    .map(([k, v]) => `    "${k.replace(/^sys\./, "")}": Color(${hexToDart(v)}),`)
    .join("\n") +
  `\n  };\n`;
writeFileSync(
  join(DIST, "flutter", "flow_tokens.dart"),
  `// Flow Design System · Flutter tokens — GENERATED. Do not hand-edit.\n` +
    `import 'package:flutter/material.dart';\n\n` +
    `abstract final class FlowTokens {\n` +
    dartScheme("canvas", canvas) +
    dartScheme("asphalt", asphalt) +
    dartScheme("brutal", brutal) +
    `}\n`,
);

const count = Object.keys(canvas).length;
console.log(
  `✓ tokens built → dist/tokens.css, tokens.json, tokens.ts, scss/_flow.scss, flutter/flow_tokens.dart (${count} resolved tokens)`,
);
